name: Test code using ESlint & build container

on: push

jobs:
  install-dependencies:
    name: Install project dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: npm install
        
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@3.1.0

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint .
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true
  
  build:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build -t cs-examen ."
        docker run cs-examen

# ${{secrets.DOCKERHUB_ACCESS_TOKEN}} --> dit staat effectief op mijn github repo, maar een image uploaden kan ik niet
